import os
import json
import re
import math
from dotenv import load_dotenv
from groq import Groq

# Load environment variables from .env file
load_dotenv()

# Initialize Groq client
api_key = os.getenv("GROQ_API_KEY")
client = Groq(api_key=api_key)

def analyze_semantic_coherence(text: str) -> float:
    """
    Signal 1: Holistic Semantic & Coherence Analysis
    Evaluates text for thematic predictability, structural hedging, semantic uniformity,
    and typical AI markers.
    
    Returns a float between 0.0 (clearly human) and 1.0 (clearly AI).
    In case of error, defaults to a neutral score of 0.5.
    """
    if not text or not text.strip():
        return 0.0

    system_prompt = (
        "You are an expert AI detection system specializing in forensic linguistic analysis. "
        "Your task is to analyze the provided text and estimate the probability that it was generated by an AI model. "
        "Assess the text on the following criteria:\n"
        "1. Semantic Uniformity: Lack of abrupt transitions or sudden shifts in narrative direction.\n"
        "2. Structural Hedging: Overuse of phrases like 'It is important to note', 'Furthermore', 'Consequently', 'In conclusion', 'Indeed'.\n"
        "3. Uniformity of Rhythm: Pacing that feels overly balanced, regular, and predictive.\n"
        "4. Vocabulary Choice: Highly structured, standard, and optimized dictionary choices with low idiomatic variance.\n\n"
        "You must return your response in a valid JSON object with the following structure:\n"
        "{\n"
        "  \"score\": <float between 0.00 and 1.00 where 0.00 is completely human-authored and 1.00 is completely AI-generated>,\n"
        "  \"reasoning\": \"<a brief 1-2 sentence explanation of the specific stylistic markers detected>\"\n"
        "}"
    )

    try:
        completion = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": text}
            ],
            response_format={"type": "json_object"},
            temperature=0.0
        )
        
        response_text = completion.choices[0].message.content
        result = json.loads(response_text)
        
        score = float(result.get("score", 0.5))
        score = max(0.0, min(1.0, score))
        return score
        
    except Exception as e:
        print(f"Error in analyze_semantic_coherence: {e}")
        return 0.5

def analyze_sentence_length_variance(text: str) -> float:
    """
    Signal 2: Sentence Length Variance (Burstiness) Heuristic
    Measures the variation of sentence lengths in the text.
    Human text typically exhibits high variance (short, punchy sentences mixed with long, 
    multi-clause structures). AI text exhibits low variance (highly uniform sentence lengths).
    
    Returns a float between 0.0 (high variance/human) and 1.0 (low variance/AI).
    Includes length smoothing for short text bodies.
    """
    cleaned = text.strip()
    if not cleaned:
        return 0.5

    # Split text into sentences based on punctuation (. ! ?) followed by whitespace
    sentences = [s.strip() for s in re.split(r'(?<=[.!?])\s+', cleaned) if s.strip()]
    
    # Calculate word counts for each sentence
    word_counts = []
    for sentence in sentences:
        # Strip remaining non-alphanumeric punctuation and split
        words = [w for w in re.split(r'\s+', re.sub(r'[^\w\s]', '', sentence)) if w]
        if words:
            word_counts.append(len(words))
            
    num_sentences = len(word_counts)
    
    # If we have fewer than 2 sentences, we cannot compute variance; return neutral score
    if num_sentences < 2:
        return 0.5
        
    # Calculate mean and variance
    mean_len = sum(word_counts) / num_sentences
    variance = sum((x - mean_len) ** 2 for x in word_counts) / num_sentences
    
    # Exponential decay mapping: 
    # High variance -> score close to 0.0 (likely human)
    # Zero variance -> score close to 1.0 (likely AI)
    # We use a scale factor of 50.0 for standard variance sensitivity
    raw_score = math.exp(-variance / 50.0)
    
    # Smoothing for short text inputs (under 4 sentences) to avoid false positives
    smoothing_weight = min(1.0, num_sentences / 4.0)
    final_score = smoothing_weight * raw_score + (1.0 - smoothing_weight) * 0.5
    
    return round(max(0.0, min(1.0, final_score)), 4)

def analyze_lexical_diversity(text: str) -> float:
    """
    Signal 3: Lexical Diversity Type-Token Ratio (TTR) Heuristic
    Computes unique words (types) divided by total words (tokens).
    AI text exhibits a standardized, optimized vocabulary range. 
    Human text exhibits more volatile diversity (either highly repetitive or uniquely dense).
    
    Returns a float between 0.0 (highly irregular/human) and 1.0 (standardized/AI).
    """
    # Tokenize words, convert to lowercase, and strip punctuation
    words = [w.lower() for w in re.split(r'\s+', re.sub(r'[^\w\s]', '', text)) if w]
    num_words = len(words)
    
    if num_words == 0:
        return 0.5
        
    unique_words = set(words)
    num_unique = len(unique_words)
    
    # Calculate Type-Token Ratio
    actual_ttr = num_unique / num_words
    
    # Standard expected TTR curve based on text length (TTR naturally drops as text grows)
    expected_ttr = 0.5 + 0.4 * math.exp(-num_words / 80.0)
    
    # Calculate deviation from the expected standard AI TTR
    deviation = abs(actual_ttr - expected_ttr)
    
    # Map deviation to a score:
    # Deviation of 0.0 -> score 1.0 (perfectly typical AI diversity)
    # Large deviation -> score close to 0.0 (irregular human distribution)
    # Sensitivity scale factor: 0.32
    raw_score = math.exp(-deviation / 0.32)
    
    # Smoothing for short text inputs (under 15 words) to pull towards neutral
    smoothing_weight = min(1.0, num_words / 15.0)
    final_score = smoothing_weight * raw_score + (1.0 - smoothing_weight) * 0.5
    
    return round(max(0.0, min(1.0, final_score)), 4)

def combine_signals(s_llm: float, s_slv: float, s_ttr: float) -> float:
    """
    Ensemble synthesis combining semantic and heuristic signals:
    Combined = 0.50 * S_llm + 0.25 * S_slv + 0.25 * S_ttr
    """
    score = 0.50 * s_llm + 0.25 * s_slv + 0.25 * s_ttr
    return round(max(0.0, min(1.0, score)), 4)

def get_transparency_label(score: float) -> tuple[str, str]:
    """
    Maps composite scores to standard transparency labels (title, body) from planning.md.
    """
    if score <= 0.35:
        return (
            "Verified Authentic",
            "This text displays the natural variations in rhythm, pacing, and vocabulary choices characteristic of direct human writing."
        )
    elif score <= 0.70:
        return (
            "Stylistically Mixed",
            "This text includes a blend of patterns. It features highly organized structures common in automated assistants alongside natural variations typical of personal expression."
        )
    else:
        return (
            "Automated Patterns Detected",
            "This text closely matches the uniform structure, repeating phrase links, and predictable sentence spacing typically generated by AI language models."
        )
